# Generated by Django 5.2.8 on 2026-04-04 16:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('parent'), name='unique_category_name_per_parent_case_insensitive'),
        ),
    ]
